# Generated by Django 4.0.6 on 2022-07-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade', models.AutoField(primary_key=True, serialize=False)),
                ('gradeName', models.CharField(choices=[('DJ1221', 'DJ1221'), ('JV0222', 'JV0222'), ('RE0522', 'RE0522'), ('AL0622', 'AL0622')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject', models.AutoField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(choices=[('Django web developement', 'Django web developement'), ('Javascript', 'Javascript'), ('Reactjs', 'Reactjs'), ('Algorithme', 'Algorithme'), ('HTML & CSS course', 'HTML & CSS course')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.subject')),
            ],
            options={
                'db_table': 'score',
            },
        ),
    ]
